OTMS/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('basetemp/', include('basetemp.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('site_admin/', include('site_admin.urls')),
    path('requestor/', include('requestor.urls')),
    path('action_officer/', include('action_officer.urls')),
    path('super_ad/', include('super_ad.urls')),
    path('travelauth/', include('travelauth.urls')),
    path('sa_action_officer/', include('sa_action_officer.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

action_officer/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.sector, name = 'sector'),
	path('dashboard/<int:pk>', views.action_officer, name = 'action-dash'),
	path('new_sub/<int:pk>', views.new_sub, name = 'newsub'),
	path('followup', views.followup, name='followup'),
	path('followup_sch', views.followup_sch, name='followup_sch'),
	path('assigned/<int:pk>', views.assigned, name = 'assigned'),
	path('details/<int:pk>', views.requestdetails, name = 'requestdetails'),
	path('detailstravel/<int:pk>', views.requestdetailstravel, name = 'requestdetailstravel'),
	path('updatedetails/<int:pk>', views.updatedetails, name = 'updatedetails'),
	path('updatedetailstravel/<int:pk>', views.updatedetailstravel, name = 'updatedetailstravel'),
	path('new_sub/take/<int:tag>', views.take, name = 'take'),
	path('new_sub/taketravel/<int:tag>', views.taketravel, name = 'taketravel'),
	path('new_sub/take/<int:tag>/<str:cat>/<str:date>/<str:ln>/<str:fn>/<str:mi>/<str:pt>/<str:frm>/<str:to>/<str:ds>/<str:tid>/<str:last>/<str:email>', views.take, name = 'take'),
	path('officers', views.officersindex, name = 'officersindex'),
	path('officers/edit/<int:pk>', views.officers_edit, name = 'officers_edit'),
	path('officers/add/', views.officers_add, name = 'officers_add'),
	path('officers/block/<int:pk>', views.block, name='block'),
	path('officers/unblock/<int:pk>', views.unblock, name='unblock'),
	path('database/travel', views.dtravelforeign, name='dtravelforeign'),
	path('database/travel/<int:pk>',views.dtravelupdateforeign, name="dtravelupdateforeign"),
	path('database/travel-local/<int:pk>',views.dtravelupdatelocal, name="dtravelupdatelocal"),
	path('database/travel-local', views.dtravellocal, name='dtravellocal'),
	path('password/<int:pk>', views.change_password, name='change_password'),
	path('database/scholarship', views.dscholarship, name='dscholarship'),
	path('database/scholarship/<int:pk>', views.dupdatescholarship, name='dupdatescholarship'),
	path('database/pendingtrainingreport/', views.pendingtrainingreport, name='pendingtrainingreport'),
	path('database/pendingtrainingreport/<int:pk>', views.updatependingtrainingreport, name='updatependingtrainingreport'),
	path('new_sub/takescholar/<int:tag>', views.takescholar, name = 'takescholar'),

	# graphical reports
	path('graphical_reports', views.travel_request_stat, name='graphical_reports'),
	# GEDSI
	path('gender_reports', views.gedsi_search, name='_gedsi_search'),
	path('disability_reports', views.disability_search, name='_disability_search'),
	path('ethnicity_reports', views.ethnicity_search, name='_ethnicity_search'),





]

zbackups/action_officer-03-31-21/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.sector, name = 'sector'),
	path('dashboard/<int:pk>', views.action_officer, name = 'action-dash'),
	path('new_sub/<int:pk>', views.new_sub, name = 'newsub'),
	path('followup', views.followup, name='followup'),
	path('followup_sch', views.followup_sch, name='followup_sch'),
	path('assigned/<int:pk>', views.assigned, name = 'assigned'),
	path('details/<int:pk>', views.requestdetails, name = 'requestdetails'),
	path('detailstravel/<int:pk>', views.requestdetailstravel, name = 'requestdetailstravel'),
	path('updatedetails/<int:pk>', views.updatedetails, name = 'updatedetails'),
	path('updatedetailstravel/<int:pk>', views.updatedetailstravel, name = 'updatedetailstravel'),
	path('new_sub/take/<int:tag>', views.take, name = 'take'),
	path('new_sub/taketravel/<int:tag>', views.taketravel, name = 'taketravel'),
	path('new_sub/take/<int:tag>/<str:cat>/<str:date>/<str:ln>/<str:fn>/<str:mi>/<str:pt>/<str:frm>/<str:to>/<str:ds>/<str:tid>/<str:last>/<str:email>', views.take, name = 'take'),
	path('officers', views.officersindex, name = 'officersindex'),
	path('officers/edit/<int:pk>', views.officers_edit, name = 'officers_edit'),
	path('officers/add/', views.officers_add, name = 'officers_add'),
	path('officers/block/<int:pk>', views.block, name='block'),
	path('officers/unblock/<int:pk>', views.unblock, name='unblock'),
	path('database/travel', views.dtravelforeign, name='dtravelforeign'),
	path('database/travel/<int:pk>',views.dtravelupdateforeign, name="dtravelupdateforeign"),
	path('database/travel-local/<int:pk>',views.dtravelupdatelocal, name="dtravelupdatelocal"),
	path('database/travel-local', views.dtravellocal, name='dtravellocal'),
	path('password/<int:pk>', views.change_password, name='change_password'),
	path('database/scholarship', views.dscholarship, name='dscholarship'),
	path('database/scholarship/<int:pk>', views.dupdatescholarship, name='dupdatescholarship'),
	path('database/pendingtrainingreport/', views.pendingtrainingreport, name='pendingtrainingreport'),
	path('database/pendingtrainingreport/<int:pk>', views.updatependingtrainingreport, name='updatependingtrainingreport'),
	path('new_sub/takescholar/<int:tag>', views.takescholar, name = 'takescholar'),

	# graphical reports
	path('graphical_reports', views.travel_request_stat, name='graphical_reports'),
	# GEDSI
	path('gender_reports', views.gedsi_search, name='_gedsi_search'),
	path('disability_reports', views.disability_search, name='_disability_search'),
	path('ethnicity_reports', views.ethnicity_search, name='_ethnicity_search'),





]

zbackups/otms-040221/OTMS/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('basetemp/', include('basetemp.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('site_admin/', include('site_admin.urls')),
    path('requestor/', include('requestor.urls')),
    path('action_officer/', include('action_officer.urls')),
    path('super_ad/', include('super_ad.urls')),
    path('travelauth/', include('travelauth.urls')),
    path('sa_action_officer/', include('sa_action_officer.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

action_officer/models.py
from django.db import models

# Create your models here.

zbackups/action_officer-03-31-21/models.py
from django.db import models

# Create your models here.

zbackups/otms-040221/action_officer/models.py
from django.db import models

# Create your models here.

action_officer/forms.py
from django import forms
from requestor.models import *
from travelauth.models import *
from login.models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import Q
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

class UpdateForm(forms.ModelForm):
    PIE_CHOICES = (
        ("1", "HRDD will register"),
        ("2", "Nominee will register"),
    )

    class Meta:
        model = Requestor
        fields = ('status', 'lacking_documents', 'ta_signed_upload')
    pie = forms.ChoiceField(choices = PIE_CHOICES, required=False, label='Choices:', )
    lacking_documents = forms.CharField(label='Lacking Documents',
                    widget=forms.TextInput(attrs={'placeholder': 'Ex. Format: Signed of copy nomination, Signed copy of REAP'}), required=False)


    def __init__(self,  *args, **kwargs):
        super(UpdateForm, self).__init__(*args, **kwargs)
        self.fields['status'].queryset = Status.objects.filter(Q(status = 'Approved') | Q(status = 'RELEASE FROM HRDD') | Q(status=  'UNABLE TO PROCEED WITH THE APPLICATION DUE TO PENDING SUBMISSION') | Q(status = 'Cancelled') | Q(status = 'New') | Q(status = 'For Evaluation') | Q(status = 'Evaluation: Failed') | Q(status = 'Passed Initial Evaluation') | Q(status = 'Evaluation: LACK DOCUMENTARY REQUIREMENTS') | Q(status = 'Scholarship Acceptance')).order_by('status')
        

class UpdateFormTravel(forms.ModelForm):
    OPTIONS = (
        (0, "Endorsement from Usec. concerned"),
        (1, "Request for Travel Authority"),
        (2, "Invitation Letter from the host/country"),
        (3, "Certificate as to no pending task/Office-in-charge"),
        (4, "Certification as to no pending admin case"),
        (5, "Service Record"),
        (6, "Certificate of Availability of Funds"),
        (7, "Estimate Breakdown of expenses"),
        (8, "Certificate as to no unliquidated cash advance"),
        (9, "Certificate as to not due to retirement/resign"),
        (10, "Certificate of undertaking"),
    )
    with_issues = forms.CharField(label='Other Issues',
                    widget=forms.TextInput(attrs={'placeholder': 'Ex. No Attachment, Unliquidated', 'style': 'width:400px'}), required=False)

    unsigned_docs = forms.CharField(label='Unsigned Docs',
                    widget=forms.TextInput(attrs={'placeholder': 'Ex Format. No Attachment, No Pending Case Unsigned', 'style': 'width:400px'}), required=False)

    wrong_attachment = forms.CharField(label='Wrong Attachment',
                    widget=forms.TextInput(attrs={'placeholder': 'Ex. Format: Walang Helmet, Backride Ko', 'style': 'width:400px'}), required=False)

    lacking_documents = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                          choices=OPTIONS, required=False)

    class Meta:
        model = TravelRequest_tbl
        fields = ('status', 'nt_gov_expense_file', 'ta_signed_upload','lacking_documents', 'with_issues', 'unsigned_docs', 'wrong_attachment' )

class DatabaseTravelUpdateForm(forms.ModelForm):
    class Meta:
        model = TravelRequest_tbl
        fields = ('gender','first_name','last_name', 'agency','position','programdates_from', 'programdates_to', 'request_category', 'program_title',
        'destination','sponsor','pre_travel_expense', 'dsa_day','clothing_allowance','remarks','rep_allowance','other_remarks',
        'ptr_submitted', 'echo_seminar','year','ptr_dnpt','acknowledgement','endorsement' )
        labels = {
            "gender": "Sex",
            "programdates_from": "Departure",
            "programdates_to": "Arrival",
            "request_category": "Type of Travel",
            "program_title": "Seminar Title/Purpose",
        }

class DatabaseTravelLocalUpdateForm(forms.ModelForm):
    class Meta:
        model = TravelRequest_tbl
        fields = ('first_name','last_name','position', 'agency','program_title','inviting_institute','venue','programdates_from','programdates_to','fee',
        'perday','other_expense', 'echo', 'training_report','received','released','remarks'  )
        labels = {
            "gender": "Sex",
            "programdates_from": "Departure",
            "programdates_to": "Arrival",
            "request_category": "Type of Travel",
            "program_title": "Seminar Title/Purpose",
        }

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.helper = FormHelper()
    #     self.helper.layout = Layout(
    #          Row(
    #             Column('gender', css_class='form-group col-md-2 mb-0'),
    #             Column('first_name', css_class='form-group col-md-5 mb-0'),
    #             Column('last_name', css_class='form-group col-md-5 mb-0'),
    #             css_class='form-row'
    #         ),
    #         Row(
    #            Column('agency', css_class='form-group col-md-3 mb-0'),
    #            Column('position', css_class='form-group col-md-3 mb-0'),
    #            Column('programdates_from', css_class='form-group col-md-3 mb-0'),
    #            Column('programdates_to', css_class='form-group col-md-3 mb-0'),
    #            css_class='form-row'
    #        ),
    #          Row(
    #             Column('request_category', css_class='form-group col-md-2 mb-0'),
    #             Column('program_title', css_class='form-group col-md-5 mb-0'),
    #             Column('destination', css_class='form-group col-md-5 mb-0'),
    #             css_class='form-row'
    #         ),
    #         Row(
    #            Column('sponsor', css_class='form-group col-md-3 mb-0'),
    #            Column('pre_travel_expense', css_class='form-group col-md-3 mb-0'),
    #            Column('dsa_day', css_class='form-group col-md-3 mb-0'),
    #             Column('clothing_allowance', css_class='form-group col-md-3 mb-0'),
    #            css_class='form-row'
    #        ),
    #        Row(
    #           Column('remarks', css_class='form-group col-md-3 mb-0'),
    #           Column('rep_allowance', css_class='form-group col-md-3 mb-0'),
    #           Column('other_remarks', css_class='form-group col-md-3 mb-0'),
    #           Column('ptr_submitted', css_class='form-group col-md-3 mb-0'),
    #           css_class='form-row',
    #         ),
    #          Row(
    #             Column('echo_seminar', css_class='form-group col-md-3 mb-0'),
    #             Column('year', css_class='form-group col-md-3 mb-0'),
    #             Column('ptr_dnpt', css_class='form-group col-md-3 mb-0'),
    #             Column('acknowledgement', css_class='form-group col-md-3 mb-0'),
    #             css_class='form-row',
    #           ),
    #          Row(
    #             Column('endorsement', css_class='form-group col-md-3 mb-0'),
    #             css_class='form-row',
    #           )
    #         ,)
            # ),
            # 'address_1',
            # 'address_2',
            # Row(
            #     Column('city', css_class='form-group col-md-6 mb-0'),
            #     Column('state', css_class='form-group col-md-4 mb-0'),
            #     Column('zip_code', css_class='form-group col-md-2 mb-0'),
            #     css_class='form-row'
            # ),
            # 'check_me_out',
            # Submit('submit', 'Sign in')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['first_name', 'last_name',
                  'email', 'username',
                  'password']

        label = {
            'password': 'Password'
        }
    def __init__(self, *args, **kwargs):
        # first call the 'real' __init__()
        super(UserForm, self).__init__(*args, **kwargs)
        # then do extra stuff:
        # self.fields['password'].widget = forms.PasswordInput(attrs={'placeholder': ''})


    def save(self):
        password = self.cleaned_data.pop('password')
        u = super().save()
        u.set_password(password)
        u.save()
        return u

class EditUserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name',
                  'email']

class ScholarshipUpdateForm(forms.ModelForm):

    class Meta:
        model = Requestor
        fields = ('gender','category','prog_title','scho_donor','location','start_date','end_date','other_expense','service_obligation','echo','training_report','remarks')

class PendingTrainingReportUpdateForm(forms.ModelForm):

    class Meta:
        model = Pending_training_report
        fields = ('first_name','last_name','middle_initial','gender','position','office','training_institution','course_name','duration_in_days',
        'programdates_from','programdates_to','program_fee','post_report_submit_date','echo_seminar_date','remarks')



class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('middle_initial','official_designation','office_or_agency','sector','mobile','role')


    def __init__(self,  *args, **kwargs):
        super(AuthorForm, self).__init__(*args, **kwargs)
        self.fields['role'].queryset = Roles.objects.filter(Q(role = 'Requestor') | Q(role = 'Action Officer'))

zbackups/action_officer-03-31-21/templates/action_officer/sample.html
	<script>
		window.location.href = "{%url 'assigned'  pk %}";
	</script>

zbackups/action_officer-03-31-21/templates/action_officer/sector.html
{% extends "basetemp/main_base.html" %}
{% block content %}
{% load static %}

<style>
.dp {
width: 300px;
height: 300px;
}
</style>
{% for item in designation %}
          {% if item.role_id == 2 %} <!-- Action Officer -->
<h6><b>SELECT DASHBOARD</b></h6>
<div class="row">

<!-- copied -->
<div class="col-lg-12 col-md-12 col-xs-12">
<center>

    </center>
    </div>
<!-- end of copied -->

<br></br>
<br></br>

<div class="col-lg-6 col-md-6 col-xs-6">
<center><a href="{% url 'action-dash' 1 %}"><img src="{% static 'basetemp/travel.svg' %}" alt="ic" class="img-responsive dp rounded"></a>
<h4><a href="{% url 'action-dash' 1 %}">TRAVEL REQUESTS</a></h4>
</center>
</div>

<div class="col-lg-6 col-md-6 col-xs-6">
<center><a href="{% url 'action-dash' 2 %}" disabled><img src="{% static 'basetemp/grad.svg' %}" alt="ic" class="img-responsive dp rounded"></a>
<h4><a href="#"disabled>SCHOLARSHIP APPLICATION</a></h4>
</center>
</div>

</div>
<!-- do not remove -->







<!-- end of table -->

<!-- dont remove by BRIAN-->
{% else %}
<center>
<h1>PAGE DOES NOT EXIST</h1>
<img src="{% static 'basetemp/empty.svg' %}" alt="ic" class="img-responsive dp rounded">
{% endif %}
</center>
{% endfor %}

</main>
{% endblock content %}

zbackups/action_officer-03-31-21/templates/action_officer/updatedetails.html
{% extends "basetemp/main_base.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}
<style>
table {
	width: 100%;
}

th, td {
	border: 1px solid #ddd;
  padding: 8px;
	font-size: 15px;
}
td:nth-child(2) {
  width:70%;
}

.breadcrumb {
    margin-bottom: 0;
    background-color: #fcfcfc;
}

</style>


<script>


	$(document).ready(function(){
	let rm = $("input#id_lacking_documents").val().replace(/[\[\]']+/g,'');
	let rm2 = rm.replace(/\s*,\s*/g, ", ");
	$("input#id_lacking_documents").val(rm2);

	if($('#id_status').val() == '20') {
		$('.resources').show();

	} else {
		$('.resources').hide();
	}

	if($('#id_status').val() == '22') {
		$('.resources-pie').show();

	} else {
		$('.resources-pie').hide();
	}

	if($('#id_status').val() == '13') {
		$('.resources-taupload').show();
		$(".resources-taupload #id_ta_signed_upload").prop('required',true);

	} else {
		$('.resources-taupload').hide();
		$(".resources-taupload #id_ta_signed_upload").prop('required',false);
	}

 $('#id_status').change(function(){
			if($('#id_status').val() == '20') {
				$('.resources').show();

			} else {
				$('.resources').hide();
			}

			if($('#id_status').val() == '22') {
				$('.resources-pie').show();

			} else {
				$('.resources-pie').hide();
			}

			if($('#id_status').val() == '13') {
				$('.resources-taupload').show();
				$('.resources-taupload #id_ta_signed_upload').prop('required',true);

			} else {
				$('.resources-taupload').hide();
				$('.resources-taupload #id_ta_signed_upload').prop('required',false);
			}
	});

	$('form').submit(function() {
		$('#btn-one').html('<span class="spinner-border spinner-border-sm mr-2" role="status" aria-hidden="true"></span>Submitting...').attr('disabled', true);
		form.submit()
	});

	});


</script>

{% if messages %}


      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert">
          <p><h6>{{ message }}</h6></p>
      </div>
      {% endfor %}



{% endif %}

<ol class="breadcrumb my-3" style="font-size: 16px;">
	 <li class="breadcrumb-item"><a href="{%url 'action-dash' 2 %}">Dashboard</a></li>
	 	 <li class="breadcrumb-item"><a href="{%url 'assigned' 2 %}">My Assigned Request</a></li>
	 <li class="breadcrumb-item active">Scholarship Details</li>
 </ol>

<div class="row">

        <div class="col-md-4 col-lg-4">
          <a href="#" target="_blank">
          <div class="widget-small info coloured-icon"><i class="icon"></i>
            <div class="info">
              <h4>Filed: {{requestors.date_filed}}</h4>
            </div>
          </div></a>
        </div>
</div>

<!-- start of table -->
<div class="container">

<!-- Request Details	 -->

	<div id="accordion">
		<div class="card">
			<div class="card-header text-white" style="background-color: #0d47a1;  ">
				<a class="card-link" data-toggle="collapse" href="#collapseOne">
					<b style="color: white !important;"> REQUEST DETAILS </b>
				</a>
			</div>
			<div id="collapseOne" class="collapse show" data-parent="#accordion">
				<div class="card-body">

	<table class='table' border="0">
		<tr>
			<td><b>Reference:</b> </td>
<td>{{ requestors.category.shortterm }}-{{requestors.date_filed|date:"y-m-d"}}-000{{ requestors.incrementor }}</td>
		</tr>
		<tr>
			<td><b>Category:</b> </td>
			<td>{{ requestors.category }}</td>
		</tr>

		<tr>
			<td><b>Sector:</b> </td>
			<td>{{ requestors.sector_for_scholarship }}</td>
		</tr>

		<tr>
			<td><b>Program Title:</b> </td>
		<td> {{ requestors.prog_title }}</td>
		</tr>

		<tr>
			<td><b>Venue:</b></td>
			<td>{{requestors.location}}</td>
		</tr>

		<tr>
			<td><b>Program Dates:</b></td>
			<td><b>From:</b> {{ requestors.start_date }} <b> To:</b> {{ requestors.end_date }}</td>
		</tr>
	</table>
</div>
</div>
</div>
</div>
<!-- Request Details	 -->

<!-- Attendee Details -->

<div id="accordion2">
	<div class="card">
		<div class="card-header text-white" style="background-color: #0d47a1;  ">
			<a class="card-link" data-toggle="collapse" href="#collapse2">
				<b style="color: white !important;"> NOMINEE'S INFORMATION </b>
			</a>
		</div>
		<div id="collapse2" class="collapse show" data-parent="#accordion2">
			<div class="card-body">

<table class='table' border="0">
	<tr>
		<td><b>Name:</b> </td>
<td>{{ requestors.first_name}} {{ requestors.last_name}}</td>
	</tr>
	<tr>
		<td><b>Position:</b> </td>
		<td>{{ requestors.position }}</td>
	</tr>

	<tr>
		<td><b>Salary Grade:</b> </td>
		<td>{{ requestors.salary_grade }}</td>
	</tr>

	<tr>
	<td><b>Office Division:</b> </td>
	<td> {{ requestors.office }}</td>
	</tr>

	<tr>
		<td><b>Email:</b></td>
		<td>{{requestors.e_mail}}</td>
	</tr>

	<tr>
		<td><b>Mobile Number:</b></td>
		<td> {{ requestors.mobile_no }}</td>
	</tr>
	<tr>
		<td><b>Office Tel. Number:</b></td>
		<td> {{ requestors.office_no}}</td>
	</tr>
</table>
</div>
</div>
</div>
</div>

<!-- Attendee Details -->


<!-- GEDSI -->
<div id="accordion3">
	<div class="card">
		<div class="card-header text-white" style="background-color: #0d47a1;  ">
			<a class="card-link" data-toggle="collapse" href="#collapse3">
				<b style="color: white !important;"> Gender Equality, Disability and Social Inclusion (GEDSI) </b>
			</a>
		</div>
		<div id="collapse3" class="collapse show" data-parent="#accordion3">
			<div class="card-body">


<table class='table' border="0">
	<tr>
		<td><b>GENDER:</b> </td>
<td>{{ requestors.gender}} </td>
	</tr>
	<tr>
		<td><b>AGE:</b> </td>
		<td>{{ requestors.age}}</td>
	</tr>

	<tr>
		<td><b>CIVIL STATUS:</b> </td>
		<td>{{ requestors.civil_status }}</td>
	</tr>

	<tr>
	<td><b>DISABILITY:</b> </td>
	<td> {{ requestors.disability }}</td>
	</tr>

	<tr>
		<td><b>ETHNICITY:</b></td>
		<td>{{requestors.ethnicity}}</td>
	</tr>

</table>
</div>
</div>
</div>
</div>

<!-- GEDSI -->

			<div id="accordion4">
				<div class="card">
					<div class="card-header text-white" style="background-color: #0d47a1;  ">
						<a class="card-link" data-toggle="collapse" href="#collapse4">
							<b style="color: white !important;"> ATTACHMENTS </b>
						</a>
					</div>
					<div id="collapse4" class="collapse show" data-parent="#accordion4">
						<div class="card-body">
		<table class='table' border="0">



			<td><b>Personal Data Sheet:</b>
				{% if requestors.personal_data_sheet %}
				<a href="{{requestors.personal_data_sheet.url}}" target="_blank">{{requestors.personal_data_sheet|default_if_none:'#'}}</a>
				{% else %}
				<i>No attachment</i>
				{%endif%}
	 </td>
		</tr>
<tr>
	<td>
			<b>Individual Performance Commitment and Review</b>:
			{% if requestors.individual_performance_commitment_and_review %}
			<a href="{{requestors.individual_performance_commitment_and_review.url}}" target="_blank">{{requestors.individual_performance_commitment_and_review|default_if_none:'#'}}</a></b>
			{% else %}
			<i>No attachment</i>
			{%endif%}
		</td>
		</tr>
		<tr>
			<td>
					<b>Potential Assessment Form</b>:
					{% if requestors.potential_assessment_form %}

					<a href="{{requestors.potential_assessment_form.url}}" target="_blank">{{requestors.potential_assessment_form|default_if_none:'#'}}</a></b>
					{% else %}
					<i>No attachment</i>
					{%endif%}
				</td>
				</tr>

				<tr>
					<td>
							<b>Signed Nomination Form</b>:
							{% if requestors.last_file %}

							<a href="{{requestors.last_file.url}}" target="_blank">{{requestors.last_file|default_if_none:'#'}}</a></b>
							{% else %}
							<i>No attachment</i>
							{%endif%}
						</td>
						</tr>





	</table>
	</div>
	</div>
</div>
	</div>
<br>

<form method="POST" enctype="multipart/form-data">
	{%csrf_token%}
<div class="row">
	<div class="form-group col-md-6 mb-0">
&nbsp &nbsp<b>{{form.status|as_crispy_field}}</b>

<div class="resources">
<b> {{form.lacking_documents|as_crispy_field}}</b>
<br>
</div>
<div class="resources-taupload">
<b>Signed Nomination: {{form.ta_signed_upload}}</b>
</div>

<div class="resources-pie">
<b>{{form.pie|as_crispy_field}}</b>
<br>
</div>

<br>
<button type="submit" class="btn btn-success" id="btn-one" position='right'>Submit</button>
	</div>
	</div>
</form>


</div>


<!-- end of table -->

<!-- dont remove by BRIAN-->
</main>
{% endblock content %}